version: '3.8'

services:
  portafolio_web:
    image: nginx:alpine
    container_name: portafolio_daniel
    volumes:
      - ./:/usr/share/nginx/html:ro
    ports:
      - "8080:80"  # Expone el portafolio en el puerto 8080 de tu VPS
    restart: always
